spring:
  application:
    name: teacher-kafka-consumer

  datasource:
    url: jdbc:postgresql://localhost:5432/testee
    username: postgres
    password: senhasegura
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    client-id: "${spring.application.name}"
    bootstrap-servers: ${KAFKA_SERVER:localhost:9092}
    consumer:
      retry: 1
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.example.kafka.contracts"
      group-id: employee-consumer
    topics:
      employee-info: ${TOPIC_TEACHER_INFO:teacher-info-topic}

server:
  port: 8083

